@baseUrl = http://localhost:3000/api/v1
@authCookie =

### Get all Playlists
GET {{baseUrl}}/playlist
Cookie: {{authCookie}}


### Get specific Playlist
@playlistId = 37i9dQZF1EIYE32WUF6sxN

GET {{baseUrl}}/playlist/{{playlistId}}
Cookie: {{authCookie}}


### Add a Spotify Playlist to our system
POST {{baseUrl}}/playlist

{
"id": "37i9dQZF1DX2CtuHQcongT",
"name": "This is SEGA SOUND TEAM",
"spotifyId": "37i9dQZF1DX2CtuHQcongT",
"categories": ["sega"]
}

### Add a Disabled Spotify Playlist to our system
POST {{baseUrl}}/playlist

{
"id": "37i9dQZF1DX2CtuHQcongT",
"name": "This is SEGA SOUND TEAM",
"spotifyId": "37i9dQZF1DX2CtuHQcongT",
"categories": ["sega"]
"enabled": false
}

